[project]
name = "firespot-backend"
version = "0.1.0"
description = "Are you in a fire spot? Discover fire-prone areas based on concentration of fuel sources."
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.3",
    "simplekml>=1.3.6",
]
